/* Generated by Yosys 0.34+55 (git sha1 672375ed0, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module counter(Clk, reset, UpOrDown, Count);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  input Clk;
  wire Clk;
  output [3:0] Count;
  reg [3:0] Count = 4'h0;
  input UpOrDown;
  wire UpOrDown;
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _38_ (
    .A(_27_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__and3_1 _39_ (
    .A(_27_),
    .B(_28_),
    .C(_31_),
    .X(_32_)
  );
  sky130_fd_sc_hd__nor3_1 _40_ (
    .A(_27_),
    .B(_28_),
    .C(_31_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__maj3_1 _41_ (
    .A(_27_),
    .B(_28_),
    .C(_31_),
    .X(_34_)
  );
  sky130_fd_sc_hd__nor2_1 _42_ (
    .A(_33_),
    .B(_34_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__nor2_1 _43_ (
    .A(_32_),
    .B(_35_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__nor2_1 _44_ (
    .A(_32_),
    .B(_33_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__xnor2_1 _45_ (
    .A(_29_),
    .B(_36_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__mux2i_1 _46_ (
    .A0(_33_),
    .A1(_32_),
    .S(_29_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__xnor2_1 _47_ (
    .A(_30_),
    .B(_37_),
    .Y(_26_)
  );
  always @(posedge Clk, posedge reset)
    if (reset) Count[0] <= 1'h0;
    else Count[0] <= _00_[0];
  always @(posedge Clk, posedge reset)
    if (reset) Count[1] <= 1'h0;
    else Count[1] <= _00_[1];
  always @(posedge Clk, posedge reset)
    if (reset) Count[2] <= 1'h0;
    else Count[2] <= _00_[2];
  always @(posedge Clk, posedge reset)
    if (reset) Count[3] <= 1'h0;
    else Count[3] <= _00_[3];
  assign _27_ = Count[0];
  assign _28_ = Count[1];
  assign _30_ = Count[3];
  assign _29_ = Count[2];
  assign _31_ = UpOrDown;
  assign _00_[0] = _23_;
  assign _00_[1] = _24_;
  assign _00_[2] = _25_;
  assign _00_[3] = _26_;
endmodule
